server {
    listen 80;
    server_name localhost;

    # Encaminha requisições feitas a /projeto-korp para o serviço go na porta 8080
    location /projeto-korp {
        proxy_pass http://http-server-projeto-korp:8080/projeto-korp;
        
        # Cabeçalhos padrão para proxy reverso
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Ajustes de timeout recomendados
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    # Bloqueio padrão para rotas não mapeadas
    location / {
        return 404 "Not Found\n";
    }
}
