{
 "title": "Monitoramento - HTTP Server Projeto Korp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}"
    }
   ]
  },
  {
   "title": "Tempo de Uptime (Atividade)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "korp_service_uptime_seconds" }
   ]
  },
  {
   "title": "Volume Total de Requisições (Acumulado)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(korp_http_requests_total) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(korp_http_requests_total[1m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  }
 ]
}